package:
  name: "hera"
  version: 0.0.1

source:
  git_url: http://mathsrv2:8081/edenn/pyhera.git

requirements:
  build:
    - python
    - setuptools
    - dask 2.9.0
    - mongoengine 0.18.2
    - xarray 0.14.1
    - pytables 3.6.1
    - scipy 1.3.2
  run:
    - python
    - dask 2.9.0
    - mongoengine 0.18.2
    - xarray 0.14.1
    - pytables 3.6.1
    - scipy 1.3.2

test:
  imports:
    - hera

about:
  home: not valid yet
