"""
Autogenerated file placeholder.
This file will be overwritten by the type generation pipeline:
  datamodel-codegen --input schema.json \
  --input-file-type jsonschema \
  --output server/models.py
"""

from pydantic import BaseModel


class Documents(BaseModel):
    sim: int
    measure: int
    cache: int


class Project(BaseModel):
    id: str
    name: str
    documents: Documents
    toolkitCount: int
